-- MySQL Script generated by MySQL Workbench
-- Thu Sep 19 05:38:52 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema clinica
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema clinica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `clinica` DEFAULT CHARACTER SET utf8mb4 ;
USE `clinica` ;

-- -----------------------------------------------------
-- Table `clinica`.`pacientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinica`.`pacientes` (
  `ID_PACIENTE` INT(11) NOT NULL,
  `NOMBRE` VARCHAR(255) NULL DEFAULT NULL,
  `fecha_nacimiento` DATETIME NULL DEFAULT NULL,
  `DIRECCION` VARCHAR(255) NULL DEFAULT NULL,
  `TELEFONO` VARCHAR(20) NULL DEFAULT NULL,
  `sexo` VARCHAR(50) NULL DEFAULT NULL,
  `correo` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_PACIENTE`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `clinica`.`medicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinica`.`medicos` (
  `ID_MEDICO` INT(11) NOT NULL,
  `NOMBRE` VARCHAR(255) NULL DEFAULT NULL,
  `ESPECIALIDAD` VARCHAR(100) NULL DEFAULT NULL,
  `TELEFONO` VARCHAR(20) NULL DEFAULT NULL,
  `correo` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_MEDICO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `clinica`.`citas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinica`.`citas` (
  `ID_CITA` INT(11) NOT NULL,
  `ID_PACIENTE` INT(11) NULL DEFAULT NULL,
  `ID_MEDICO` INT(11) NULL DEFAULT NULL,
  `FECHA_CITA` DATETIME NULL DEFAULT NULL,
  `MOTIVO` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_CITA`),
  INDEX `ID_PACIENTE` (`ID_PACIENTE` ASC),
  INDEX `ID_MEDICO` (`ID_MEDICO` ASC),
  CONSTRAINT `citas_ibfk_1`
    FOREIGN KEY (`ID_PACIENTE`)
    REFERENCES `clinica`.`pacientes` (`ID_PACIENTE`),
  CONSTRAINT `citas_ibfk_2`
    FOREIGN KEY (`ID_MEDICO`)
    REFERENCES `clinica`.`medicos` (`ID_MEDICO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `clinica`.`tratamientos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinica`.`tratamientos` (
  `ID_TRATAMIENTO` INT(11) NOT NULL,
  `ID_CITA` INT(11) NULL DEFAULT NULL,
  `DESCRIPCION` VARCHAR(500) NULL DEFAULT NULL,
  `COSTO` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_TRATAMIENTO`),
  INDEX `ID_CITA` (`ID_CITA` ASC),
  CONSTRAINT `tratamientos_ibfk_1`
    FOREIGN KEY (`ID_CITA`)
    REFERENCES `clinica`.`citas` (`ID_CITA`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
